### ISSUE TITLE
[Possible crash] Ci 03 Name: Jade Sucks

### ISSUE THREAD

**Issue by wickedcody123456** [mudjs/game#4]
Report
Report information:
the front end code is crashing on deleting the last character. 
Reason for crash:
did not look into it.

![capture](https://user-images.githubusercontent.com/7199303/39672645-7b7760ae-516d-11e8-9557-552e8f9f9681.PNG)
 test server 1 modified Front end code to make it looks better [old verison]. ^

![capture](https://user-images.githubusercontent.com/7199303/39672751-81996de0-516f-11e8-9ea9-6eda61d61b55.PNG) 
test server 2 new version unmodified. ^

**Comment by wickedcody123456** [comment]
i will look into that code area soonish

**Comment by wickedcody123456** [comment]
looks like you can patch it by adding this
		if(Character.length >= 1)
			return
		else
to the character route after line 39.
should looks like this
    {
		if(Character.length >= 1)
			return
		else
        res.redirect('/login');
    } :)

**Comment by wickedcody123456** [comment]
this patch for the delete looks like it works.
            if (name.length >= 1){
            delete req.session.character;
			} else {
				return
			}

**Comment by envis10n** [comment]
Having a problem reproducing the crash, but I will add a check anyway

**Comment by envis10n** [comment]
Should be fixed now.
