### ISSUE TITLE
[one minor bug and one possible biggish bug] [command /move \ " "] [version caadda4] ci 05 - ci 06

### ISSUE THREAD

**Issue by wickedcody123456** [mudjs/game#6]
when you use /move aw it prints out two can move in time and moved undefined. possible due to w being a location. it also does it for /move hw did not try any other combos.

**Comment by wickedcody123456** [comment]
On the private server with two characters one incognito \ one none incognito. cods 
The Local Gm:
x: 512
y: 398
z: 629
Clark (totally not super man right!?????):
x: 512
y: 512
z: 658

when i message it does not show on the other. even with yell

**Comment by envis10n** [comment]
The first one would appear to be an issue, possibly. The second is not. Distance is compared in 2D due to the differences in Z axis being fairly great between 2 tiles. From 512,512 to 512,398 is a distance of 118 tiles. Yell is only 3 tiles, while say is less than 1 tile.

**Comment by envis10n** [comment]
This is now fixed.
